spring:
  social:
    twitter:
      app-id: test
      app-secret: test
    facebook:
      app-id: test
      app-secret: test
    mason:
      app-id: test
      app-secret: test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/masonSocial
    username: masonSocial
    password: masonSocial
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
